M48
; DRILL file {KiCad 8.0.2} date 2025-03-15T23:16:25-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-15T23:16:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X116.22Y-74.025
X116.22Y-120.975
X140.73Y-74.025
X140.73Y-120.975
M30
